### PR TITLE
Wrote a consent form which can be used in the GUI and published on th…

### PR DESCRIPTION
**Pull request by agrabeli**
…e main website

### CODE REVIEW

**Comment by anadahz** [comment]
There is already an [informed consent](https://github.com/TheTorProject/ooni-spec/tree/master/informed-consent). I think it makes sense to edit the specific files and maybe add new as needed in the 'informed-consent' directory.

**Comment by hellais** [comment]
@anadahz this is something different though. It's the actual form that will be presented to the user upon first running ooniprobe (or on installation) to agree express that they understand the risks associated with performing network measurements with ooniprobe.

The other documents inside of informed consent are too verbose to be shown to every user and we should probably be cross referencing them in the form for people that want more information.

The `informed-consent-long`, I believe, should be entirely removed in favour of this.

**Comment by anadahz** [comment]
@hellais that makes more sense we should update/remove/merge what is needed not needed and place these files in the relevant directory.

**Comment by hellais** [comment]
This is now inside of the ooni web UI. I think we can close this PR.

**Pull request closed without merging**
